const = {
	DOTA_UNIT_ORDER = {},
	OVERHEAD_ALERT = {
		 OVERHEAD_ALERT_GOLD
		,OVERHEAD_ALERT_DENY
		,OVERHEAD_ALERT_CRITICAL
		,OVERHEAD_ALERT_XP
		,OVERHEAD_ALERT_BONUS_SPELL_DAMAGE
		,OVERHEAD_ALERT_MISS
		,OVERHEAD_ALERT_DAMAGE
		,OVERHEAD_ALERT_EVADE
		,OVERHEAD_ALERT_BLOCK
		,OVERHEAD_ALERT_BONUS_POISON_DAMAGE
		,OVERHEAD_ALERT_HEAL
		,OVERHEAD_ALERT_MANA_ADD
		,OVERHEAD_ALERT_MANA_LOSS
		,OVERHEAD_ALERT_LAST_HIT_EARLY
		,OVERHEAD_ALERT_LAST_HIT_CLOSE
		,OVERHEAD_ALERT_LAST_HIT_MISS
		,OVERHEAD_ALERT_MAGICAL_BLOCK
		,OVERHEAD_ALERT_INCOMING_DAMAGE
		,OVERHEAD_ALERT_OUTGOING_DAMAGE
		,OVERHEAD_ALERT_DISABLE_RESIST
		,OVERHEAD_ALERT_DEATH
	},
	DOTA_PROJECTILE_ATTACHMENT = {
		 DOTA_PROJECTILE_ATTACHMENT_NONE
		,DOTA_PROJECTILE_ATTACHMENT_ATTACK_1
		,DOTA_PROJECTILE_ATTACHMENT_ATTACK_2
		,DOTA_PROJECTILE_ATTACHMENT_HITLOCATION
		,DOTA_PROJECTILE_ATTACHMENT_ATTACK_3
		,DOTA_PROJECTILE_ATTACHMENT_ATTACK_4
		,DOTA_PROJECTILE_ATTACHMENT_LAST
	},
	DOTA_ITEM = {
		 DOTA_ITEM_MAX-- = 17
		,DOTA_ITEM_INVENTORY_SIZE-- = 9
		,DOTA_ITEM_STASH_SIZE-- = 6
		,DOTA_ITEM_STASH_MIN-- = 9
		,DOTA_ITEM_STASH_MAX-- = 15
		,DOTA_ITEM_TRANSIENT_ITEM-- = 15
		,DOTA_ITEM_TRANSIENT_RECIPE-- = 16
		,DOTA_ITEM_TRANSIENT_CAST_ITEM-- = 18
	},
	PATTACH = {
		 PATTACH_INVALID
		,PATTACH_ABSORIGIN
		,PATTACH_ABSORIGIN_FOLLOW
		,PATTACH_CUSTOMORIGIN
		,PATTACH_CUSTOMORIGIN_FOLLOW
		,PATTACH_POINT
		,PATTACH_POINT_FOLLOW
		,PATTACH_EYES_FOLLOW
		,PATTACH_OVERHEAD_FOLLOW
		,PATTACH_WORLDORIGIN
		,PATTACH_ROOTBONE_FOLLOW
		,PATTACH_RENDERORIGIN_FOLLOW 
		,PATTACH_MAIN_VIEW
		,PATTACH_WATERWAKE
		,PATTACH_CENTER_FOLLOW
		,MAX_PATTACH_TYPES
	},
	DOTA_CONNECTION_STATE = {
		 DOTA_CONNECTION_STATE_UNKNOWN
		,DOTA_CONNECTION_STATE_NOT_YET_CONNECTED
		,DOTA_CONNECTION_STATE_CONNECTED
		,DOTA_CONNECTION_STATE_DISCONNECTED
		,DOTA_CONNECTION_STATE_ABANDONED
		,DOTA_CONNECTION_STATE_LOADING
		,DOTA_CONNECTION_STATE_FAILED
	}
}


const.DOTA_UNIT_ORDER.move = {
	 DOTA_UNIT_ORDER_MOVE_TO_DIRECTION
	,DOTA_UNIT_ORDER_MOVE_TO_POSITION
	,DOTA_UNIT_ORDER_MOVE_TO_TARGET
	,DOTA_UNIT_ORDER_HOLD_POSITION
	,DOTA_UNIT_ORDER_PATROL
	,DOTA_UNIT_ORDER_STOP
}
const.DOTA_UNIT_ORDER.item = {
	 DOTA_UNIT_ORDER_SET_ITEM_COMBINE_LOCK
	,DOTA_UNIT_ORDER_EJECT_ITEM_FROM_STASH
	,DOTA_UNIT_ORDER_DISASSEMBLE_ITEM
	,DOTA_UNIT_ORDER_PURCHASE_ITEM
	,DOTA_UNIT_ORDER_PICKUP_ITEM
	,DOTA_UNIT_ORDER_PICKUP_RUNE
	,DOTA_UNIT_ORDER_MOVE_ITEM
	,DOTA_UNIT_ORDER_SELL_ITEM
	,DOTA_UNIT_ORDER_GIVE_ITEM
	,DOTA_UNIT_ORDER_DROP_ITEM
}
const.DOTA_UNIT_ORDER.cast = {
	 DOTA_UNIT_ORDER_CAST_TARGET_TREE
	,DOTA_UNIT_ORDER_CAST_TOGGLE_AUTO
	,DOTA_UNIT_ORDER_CAST_NO_TARGET
	,DOTA_UNIT_ORDER_CAST_POSITION
	,DOTA_UNIT_ORDER_CAST_TARGET
	,DOTA_UNIT_ORDER_CAST_TOGGLE
	,DOTA_UNIT_ORDER_CAST_RUNE
}
const.DOTA_UNIT_ORDER.attack = {
	 DOTA_UNIT_ORDER_ATTACK_TARGET
	,DOTA_UNIT_ORDER_ATTACK_MOVE
}
const.DOTA_UNIT_ORDER.other = {
	 DOTA_UNIT_ORDER_VECTOR_TARGET_POSITION
	,DOTA_UNIT_ORDER_VECTOR_TARGET_CANCELED
	,DOTA_UNIT_ORDER_CAST_RIVER_PAINT
	,DOTA_UNIT_ORDER_TRAIN_ABILITY
	,DOTA_UNIT_ORDER_PING_ABILITY
	,DOTA_UNIT_ORDER_CONTINUE
	,DOTA_UNIT_ORDER_BUYBACK
	,DOTA_UNIT_ORDER_TAUNT
	,DOTA_UNIT_ORDER_GLYPH
	,DOTA_UNIT_ORDER_RADAR
	,DOTA_UNIT_ORDER_NONE
}
const.DOTA_UNIT_ORDER.all = {
	 DOTA_UNIT_ORDER_NONE
	,DOTA_UNIT_ORDER_MOVE_TO_POSITION
	,DOTA_UNIT_ORDER_MOVE_TO_TARGET
	,DOTA_UNIT_ORDER_ATTACK_MOVE
	,DOTA_UNIT_ORDER_ATTACK_TARGET
	,DOTA_UNIT_ORDER_CAST_POSITION
	,DOTA_UNIT_ORDER_CAST_TARGET
	,DOTA_UNIT_ORDER_CAST_TARGET_TREE
	,DOTA_UNIT_ORDER_CAST_NO_TARGET
	,DOTA_UNIT_ORDER_CAST_TOGGLE
	,DOTA_UNIT_ORDER_HOLD_POSITION
	,DOTA_UNIT_ORDER_TRAIN_ABILITY
	,DOTA_UNIT_ORDER_DROP_ITEM
	,DOTA_UNIT_ORDER_GIVE_ITEM
	,DOTA_UNIT_ORDER_PICKUP_ITEM
	,DOTA_UNIT_ORDER_PICKUP_RUNE
	,DOTA_UNIT_ORDER_PURCHASE_ITEM
	,DOTA_UNIT_ORDER_SELL_ITEM
	,DOTA_UNIT_ORDER_DISASSEMBLE_ITEM
	,DOTA_UNIT_ORDER_MOVE_ITEM
	,DOTA_UNIT_ORDER_CAST_TOGGLE_AUTO
	,DOTA_UNIT_ORDER_STOP
	,DOTA_UNIT_ORDER_TAUNT
	,DOTA_UNIT_ORDER_BUYBACK
	,DOTA_UNIT_ORDER_GLYPH
	,DOTA_UNIT_ORDER_EJECT_ITEM_FROM_STASH
	,DOTA_UNIT_ORDER_CAST_RUNE
	,DOTA_UNIT_ORDER_PING_ABILITY
	,DOTA_UNIT_ORDER_MOVE_TO_DIRECTION
	,DOTA_UNIT_ORDER_PATROL
	,DOTA_UNIT_ORDER_VECTOR_TARGET_POSITION
	,DOTA_UNIT_ORDER_RADAR
	,DOTA_UNIT_ORDER_SET_ITEM_COMBINE_LOCK
	,DOTA_UNIT_ORDER_CONTINUE
	,DOTA_UNIT_ORDER_VECTOR_TARGET_CANCELED
	,DOTA_UNIT_ORDER_CAST_RIVER_PAINT
}



function constants(str, t)
	if str and const[str] then
		if not t then
			return const[str]
		else
			if const[str][t] then
				return const[str][t]
			end
		end
	end
	return const
end

return const